apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir
  labels:
    app.kubernetes.io/name: mimir
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mimir
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 9009
          volumeMounts:
            - name: mimir-config
              mountPath: /etc/mimir/config.yaml
              subPath: config.yaml
          command:
            - mimir
            - --config.file=/etc/mimir/config.yaml
      volumes:
        - name: mimir-config
          configMap:
            name: mimir
